version: '3'
services:
  jenkins:
#    build: ./jenkins if gi
    image: getintodevops/jenkins-withdocker:lts-docker18.06.0
    container_name: jenkins
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "9060:9060"
      - "9080:9080"
  nginx-nexus:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
      - "7070:7070"
    links:
      - nexus
    command: [ nginx, '-g', 'daemon off;' ]
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    expose:
      - 9000
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres:12.4-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  nexus-data: {}
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: